pub fn map_data(conn: &simconnectsdk::SimConnector) {
    conn.add_data_definition(0, "Plane Latitude", "Radians", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "Plane Longitude", "Radians", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "PLANE ALTITUDE", "Feet", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    
    conn.add_data_definition(0, "PLANE PITCH DEGREES", "Radians", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "PLANE BANK DEGREES", "Radians", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "PLANE HEADING DEGREES MAGNETIC", "Radians", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);

    conn.add_data_definition(0, "GENERAL ENG THROTTLE LEVER POSITION:1", "Percent", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "GENERAL ENG MIXTURE LEVER POSITION:1", "Percent", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    // conn.add_data_definition(0, "GENERAL ENG PROP LEVER POSITION:1", "Percent", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);

    conn.add_data_definition(0, "VELOCITY WORLD X", "Feet per second", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "VELOCITY WORLD Y", "Feet per second", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "VELOCITY WORLD Z", "Feet per second", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "ACCELERATION WORLD X", "Feet per second squared", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "ACCELERATION WORLD Y", "Feet per second squared", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "ACCELERATION WORLD Z", "Feet per second squared", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "ROTATION VELOCITY BODY X", "Feet per second", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "ROTATION VELOCITY BODY Y", "Feet per second", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "ROTATION VELOCITY BODY Z", "Feet per second", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);

    conn.add_data_definition(0, "AIRSPEED TRUE", "Knots", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "YOKE X POSITION", "Position", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "YOKE Y POSITION", "Position", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);

    conn.add_data_definition(0, "RUDDER PEDAL POSITION", "Position", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "RUDDER POSITION", "Position", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "ELEVATOR POSITION", "Position", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "AILERON POSITION", "Position", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);

    conn.add_data_definition(0, "ELEVATOR TRIM POSITION", "Radians", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "RUDDER POSITION", "Position", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "BRAKE LEFT POSITION", "Position", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "BRAKE RIGHT POSITION", "Position", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    conn.add_data_definition(0, "FLAPS HANDLE INDEX", "Number", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);

    // conn.add_data_definition(0, "GEAR HANDLE POSITION", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, u32::MAX);
    // conn.add_data_definition(0, "GEAR CENTER POSITION", "Percent Over 100", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    // conn.add_data_definition(0, "GEAR LEFT POSITION", "Percent Over 100", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);
    // conn.add_data_definition(0, "GEAR RIGHT POSITION", "Percent Over 100", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_FLOAT64, u32::MAX);

    conn.add_data_definition(1, "LIGHT STROBE", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 0);
    conn.add_data_definition(1, "LIGHT PANEL", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 1);
    conn.add_data_definition(1, "LIGHT LANDING", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 2);
    conn.add_data_definition(1, "LIGHT TAXI", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 3);
    conn.add_data_definition(1, "LIGHT BEACON", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 4);
    conn.add_data_definition(1, "LIGHT NAV", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 5);
    conn.add_data_definition(1, "LIGHT LOGO", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 6);
    conn.add_data_definition(1, "LIGHT WING", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 7);
    conn.add_data_definition(1, "LIGHT RECOGNITION", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 8);
    conn.add_data_definition(1, "LIGHT CABIN", "Bool", simconnectsdk::SIMCONNECT_DATATYPE_SIMCONNECT_DATATYPE_INT32, 9);
    
}

pub fn map_events(conn: &simconnectsdk::SimConnector) {
    let event_list = [    
        "SLING_PICKUP_RELEASE",
        "HOIST_SWITCH_EXTEND",
        "HOIST_SWITCH_RETRACT",
        "HOIST_SWITCH_SET",
        "HOIST_DEPLOY_TOGGLE",
        "HOIST_DEPLOY_SET",
        "ANTIDETONATION_TANK_VALVE_TOGGLE",
        "NITROUS_TANK_VALVE_TOGGLE",
        "TAKEOFF_ASSIST_ARM_TOGGLE",
        "TAKEOFF_ASSIST_ARM_SET",
        "TAKEOFF_ASSIST_FIRE",
        "TOGGLE_LAUNCH_BAR_SWITCH",
        "SET_LAUNCH_BAR_SWITCH",
        "REPAIR_AND_REFUEL",
        "DME_SELECT",
        "FUEL_DUMP_TOGGLE",
        "VIEW_COCKPIT_FORWARD",
        "VIEW_VIRTUAL_COCKPIT_FORWARD",
        "TOW_PLANE_RELEASE",
        "TOW_PLANE_REQUEST",
        "REQUEST_FUEL_KEY",
        "RELEASE_DROPPABLE_OBJECTS",
        "VIEW_PANEL_ALPHA_SET",
        "VIEW_PANEL_ALPHA_SELECT",
        "VIEW_PANEL_ALPHA_INC",
        "VIEW_PANEL_ALPHA_DEC",
        "VIEW_LINKING_SET",
        "VIEW_LINKING_TOGGLE",
        "RADIO_SELECTED_DME_IDENT_ENABLE",
        "RADIO_SELECTED_DME_IDENT_DISABLE",
        "RADIO_SELECTED_DME_IDENT_SET",
        "RADIO_SELECTED_DME_IDENT_TOGGLE",
        "GAUGE_KEYSTROKE",
        "SIMUI_WINDOW_HIDESHOW",
        "TOGGLE_VARIOMETER_SWITCH",
        "TOGGLE_TURN_INDICATOR_SWITCH",
        "VIEW_WINDOW_TITLES_TOGGLE",
        "AXIS_PAN_PITCH",
        "AXIS_PAN_HEADING",
        "AXIS_PAN_TILT",
        "VIEW_AXIS_INDICATOR_CYCLE",
        "VIEW_MAP_ORIENTATION_CYCLE",
        "TOGGLE_JETWAY",
        "RETRACT_FLOAT_SWITCH_DEC",
        "RETRACT_FLOAT_SWITCH_INC",
        "TOGGLE_WATER_BALLAST_VALVE",
        "VIEW_CHASE_DISTANCE_ADD",
        "VIEW_CHASE_DISTANCE_SUB",
        "APU_STARTER",
        "APU_OFF_SWITCH",
        "APU_GENERATOR_SWITCH_TOGGLE",
        "APU_GENERATOR_SWITCH_SET",
        "EXTINGUISH_ENGINE_FIRE",
        "AP_MAX_BANK_INC",
        "AP_MAX_BANK_DEC",
        "AP_N1_HOLD",
        "AP_N1_REF_INC",
        "AP_N1_REF_DEC",
        "AP_N1_REF_SET",
        "HYDRAULIC_SWITCH_TOGGLE",
        "BLEED_AIR_SOURCE_CONTROL_INC",
        "BLEED_AIR_SOURCE_CONTROL_DEC",
        "TURBINE_IGNITION_SWITCH_TOGGLE",
        "CABIN_NO_SMOKING_ALERT_SWITCH_TOGGLE",
        "CABIN_SEATBELTS_ALERT_SWITCH_TOGGLE",
        "ANTISKID_BRAKES_TOGGLE",
        "GPWS_SWITCH_TOGGLE",
        "VIDEO_RECORD_TOGGLE",
        "TOGGLE_AIRPORT_NAME_DISPLAY",
        "CAPTURE_SCREENSHOT",
        "MOUSE_LOOK_TOGGLE",
        "YAXIS_INVERT_TOGGLE",
        "AUTORUDDER_TOGGLE",
        "FLY_BY_WIRE_ELAC_TOGGLE",
        "FLY_BY_WIRE_FAC_TOGGLE",
        "FLY_BY_WIRE_SEC_TOGGLE",
        "MANUAL_FUEL_PRESSURE_PUMP",
        "STEERING_INC",
        "STEERING_DEC",
        "STEERING_SET",
        "PRESSURIZATION_PRESSURE_ALT_INC",
        "PRESSURIZATION_PRESSURE_ALT_DEC",
        "PRESSURIZATION_CLIMB_RATE_INC",
        "PRESSURIZATION_CLIMB_RATE_DEC",
        "PRESSURIZATION_PRESSURE_DUMP_SWTICH",
        "FUEL_SELECTOR_LEFT_MAIN",
        "FUEL_SELECTOR_2_LEFT_MAIN",
        "FUEL_SELECTOR_3_LEFT_MAIN",
        "FUEL_SELECTOR_4_LEFT_MAIN",
        "FUEL_SELECTOR_RIGHT_MAIN",
        "FUEL_SELECTOR_2_RIGHT_MAIN",
        "FUEL_SELECTOR_3_RIGHT_MAIN",
        "FUEL_SELECTOR_4_RIGHT_MAIN",
        "POINT_OF_INTEREST_TOGGLE_POINTER",
        "POINT_OF_INTEREST_CYCLE_PREVIOUS",
        "POINT_OF_INTEREST_CYCLE_NEXT",
        "G1000_PFD_FLIGHTPLAN_BUTTON",
        "G1000_PFD_PROCEDURE_BUTTON",
        "G1000_PFD_ZOOMIN_BUTTON",
        "G1000_PFD_ZOOMOUT_BUTTON",
        "G1000_PFD_DIRECTTO_BUTTON",
        "G1000_PFD_MENU_BUTTON",
        "G1000_PFD_CLEAR_BUTTON",
        "G1000_PFD_ENTER_BUTTON",
        "G1000_PFD_CURSOR_BUTTON",
        "G1000_PFD_GROUP_KNOB_INC",
        "G1000_PFD_GROUP_KNOB_DEC",
        "G1000_PFD_PAGE_KNOB_INC",
        "G1000_PFD_PAGE_KNOB_DEC",
        "G1000_PFD_SOFTKEY1",
        "G1000_MFD_FLIGHTPLAN_BUTTON",
        "G1000_MFD_PROCEDURE_BUTTON",
        "G1000_MFD_ZOOMIN_BUTTON",
        "G1000_MFD_ZOOMOUT_BUTTON",
        "G1000_MFD_DIRECTTO_BUTTON",
        "G1000_MFD_MENU_BUTTON",
        "G1000_MFD_CLEAR_BUTTON",
        "G1000_MFD_ENTER_BUTTON",
        "G1000_MFD_CURSOR_BUTTON",
        "G1000_MFD_GROUP_KNOB_INC",
        "G1000_MFD_GROUP_KNOB_DEC",
        "G1000_MFD_PAGE_KNOB_INC",
        "G1000_MFD_PAGE_KNOB_DEC",
        "G1000_MFD_SOFTKEY1",
        "AXIS_PROPELLER_SET",
        "AXIS_PROPELLER1_SET",
        "AXIS_PROPELLER2_SET",
        "AXIS_PROPELLER3_SET",
        "AXIS_PROPELLER4_SET",
        "JET_STARTER",
        "MAGNETO_SET",
        "TOGGLE_STARTER1",
        "TOGGLE_STARTER2",
        "TOGGLE_STARTER3",
        "TOGGLE_STARTER4",
        "TOGGLE_ALL_STARTERS",
        "ENGINE_AUTO_START",
        "ENGINE_AUTO_SHUTDOWN",
        "MAGNETO",
        "MAGNETO_DECR",
        "MAGNETO_INCR",
        "MAGNETO1_OFF",
        "MAGNETO1_BOTH",
        "MAGNETO1_START",
        "MAGNETO2_OFF",
        "MAGNETO2_BOTH",
        "MAGNETO2_START",
        "MAGNETO3_OFF",
        "MAGNETO3_BOTH",
        "MAGNETO3_START",
        "MAGNETO4_OFF",
        "MAGNETO4_BOTH",
        "MAGNETO4_START",
        "MAGNETO_OFF",
        "MAGNETO_RIGHT",
        "MAGNETO_LEFT",
        "MAGNETO_BOTH",
        "MAGNETO_START",
        "MAGNETO1_DECR",
        "MAGNETO1_INCR",
        "MAGNETO2_DECR",
        "MAGNETO2_INCR",
        "MAGNETO3_DECR",
        "MAGNETO3_INCR",
        "MAGNETO4_DECR",
        "MAGNETO4_INCR",
        "MAGNETO1_SET",
        "MAGNETO2_SET",
        "MAGNETO3_SET",
        "MAGNETO4_SET",
        "ANTI_ICE_ON",
        "ANTI_ICE_OFF",
        "ANTI_ICE_SET",
        "ANTI_ICE_TOGGLE",
        "ANTI_ICE_TOGGLE_ENG1",
        "ANTI_ICE_TOGGLE_ENG2",
        "ANTI_ICE_TOGGLE_ENG3",
        "ANTI_ICE_TOGGLE_ENG4",
        "ANTI_ICE_SET_ENG1",
        "ANTI_ICE_SET_ENG2",
        "ANTI_ICE_SET_ENG3",
        "ANTI_ICE_SET_ENG4",
        "TOGGLE_FUEL_VALVE_ALL",
        "COWLFLAP1_SET",
        "COWLFLAP2_SET",
        "COWLFLAP3_SET",
        "COWLFLAP4_SET",
        "INC_COWL_FLAPS",
        "DEC_COWL_FLAPS",
        "INC_COWL_FLAPS1",
        "DEC_COWL_FLAPS1",
        "INC_COWL_FLAPS2",
        "DEC_COWL_FLAPS2",
        "INC_COWL_FLAPS3",
        "DEC_COWL_FLAPS3",
        "INC_COWL_FLAPS4",
        "DEC_COWL_FLAPS4",
        "FLAPS_UP",
        "FLAPS_1",
        "FLAPS_2",
        "FLAPS_3",
        "FLAPS_DOWN",
        "FUEL_PUMP",
        "TOGGLE_ELECT_FUEL_PUMP",
        "ENGINE_PRIMER",
        "TOGGLE_PRIMER",
        "TOGGLE_PRIMER1",
        "TOGGLE_PRIMER2",
        "TOGGLE_PRIMER3",
        "TOGGLE_PRIMER4",
        "TOGGLE_FEATHER_SWITCHES",
        "TOGGLE_FEATHER_SWITCH_1",
        "TOGGLE_FEATHER_SWITCH_2",
        "TOGGLE_FEATHER_SWITCH_3",
        "TOGGLE_FEATHER_SWITCH_4",
        "TOGGLE_PROPELLER_SYNC",
        "TOGGLE_AUTOFEATHER_ARM",
        "TOGGLE_AFTERBURNER",
        "TOGGLE_AFTERBURNER1",
        "TOGGLE_AFTERBURNER2",
        "TOGGLE_AFTERBURNER3",
        "TOGGLE_AFTERBURNER4",
        "ENGINE",
        "AP_MASTER",
        "AUTOPILOT_OFF",
        "AUTOPILOT_ON",
        "YAW_DAMPER_TOGGLE",
        "AP_PANEL_HEADING_HOLD",
        "AP_PANEL_ALTITUDE_HOLD",
        "AP_ATT_HOLD_ON",
        "AP_LOC_HOLD_ON",
        "AP_APR_HOLD_ON",
        "AP_HDG_HOLD_ON",
        "AP_ALT_HOLD_ON",
        "AP_WING_LEVELER_ON",
        "AP_BC_HOLD_ON",
        "AP_NAV1_HOLD_ON",
        "AP_ATT_HOLD_OFF",
        "AP_LOC_HOLD_OFF",
        "AP_APR_HOLD_OFF",
        "AP_HDG_HOLD_OFF",
        "AP_ALT_HOLD_OFF",
        "AP_WING_LEVELER_OFF",
        "AP_BC_HOLD_OFF",
        "AP_NAV1_HOLD_OFF",
        "AP_AIRSPEED_HOLD",
        "AUTO_THROTTLE_ARM",
        "AUTO_THROTTLE_TO_GA",
        "HEADING_BUG_INC",
        "HEADING_BUG_DEC",
        "HEADING_BUG_SET",
        "AP_PANEL_SPEED_HOLD",
        "AP_ALT_VAR_INC",
        "AP_ALT_VAR_DEC",
        "AP_VS_VAR_INC",
        "AP_VS_VAR_DEC",
        "AP_SPD_VAR_INC",
        "AP_SPD_VAR_DEC",
        "AP_PANEL_MACH_HOLD",
        "AP_MACH_VAR_INC",
        "AP_MACH_VAR_DEC",
        "AP_MACH_HOLD",
        "AP_ALT_VAR_SET_METRIC",
        "AP_VS_VAR_SET_ENGLISH",
        "AP_SPD_VAR_SET",
        "AP_MACH_VAR_SET",
        "YAW_DAMPER_ON",
        "YAW_DAMPER_OFF",
        "YAW_DAMPER_SET",
        "AP_AIRSPEED_ON",
        "AP_AIRSPEED_OFF",
        "AP_AIRSPEED_SET",
        "AP_MACH_ON",
        "AP_MACH_OFF",
        "AP_MACH_SET",
        "AP_PANEL_ALTITUDE_ON",
        "AP_PANEL_ALTITUDE_OFF",
        "AP_PANEL_ALTITUDE_SET",
        "AP_PANEL_HEADING_ON",
        "AP_PANEL_HEADING_OFF",
        "AP_PANEL_HEADING_SET",
        "AP_PANEL_MACH_ON",
        "AP_PANEL_MACH_OFF",
        "AP_PANEL_MACH_SET",
        "AP_PANEL_SPEED_ON",
        "AP_PANEL_SPEED_OFF",
        "AP_PANEL_SPEED_SET",
        "AP_ALT_VAR_SET_ENGLISH",
        "AP_VS_VAR_SET_METRIC",
        "TOGGLE_FLIGHT_DIRECTOR",
        "SYNC_FLIGHT_DIRECTOR_PITCH",
        "INCREASE_AUTOBRAKE_CONTROL",
        "DECREASE_AUTOBRAKE_CONTROL",
        "AP_PANEL_SPEED_HOLD_TOGGLE",
        "AP_PANEL_MACH_HOLD_TOGGLE",
        "AP_NAV_SELECT_SET",
        "HEADING_BUG_SELECT",
        "ALTITUDE_BUG_SELECT",
        "VSI_BUG_SELECT",
        "AIRSPEED_BUG_SELECT",
        "AP_PITCH_REF_INC_UP",
        "AP_PITCH_REF_INC_DN",
        "AP_PITCH_REF_SELECT",
        "AP_ATT_HOLD",
        "AP_LOC_HOLD",
        "AP_APR_HOLD",
        "AP_HDG_HOLD",
        "AP_ALT_HOLD",
        "AP_WING_LEVELER",
        "AP_BC_HOLD",
        "AP_NAV1_HOLD",
        "FUEL_SELECTOR_OFF",
        "FUEL_SELECTOR_ALL",
        "FUEL_SELECTOR_LEFT",
        "FUEL_SELECTOR_RIGHT",
        "FUEL_SELECTOR_LEFT_AUX",
        "FUEL_SELECTOR_RIGHT_AUX",
        "FUEL_SELECTOR_CENTER",
        "FUEL_SELECTOR_SET",
        "FUEL_SELECTOR_2_OFF",
        "FUEL_SELECTOR_2_ALL",
        "FUEL_SELECTOR_2_LEFT",
        "FUEL_SELECTOR_2_RIGHT",
        "FUEL_SELECTOR_2_LEFT_AUX",
        "FUEL_SELECTOR_2_RIGHT_AUX",
        "FUEL_SELECTOR_2_CENTER",
        "FUEL_SELECTOR_2_SET",
        "FUEL_SELECTOR_3_OFF",
        "FUEL_SELECTOR_3_ALL",
        "FUEL_SELECTOR_3_LEFT",
        "FUEL_SELECTOR_3_RIGHT",
        "FUEL_SELECTOR_3_LEFT_AUX",
        "FUEL_SELECTOR_3_RIGHT_AUX",
        "FUEL_SELECTOR_3_CENTER",
        "FUEL_SELECTOR_3_SET",
        "FUEL_SELECTOR_4_OFF",
        "FUEL_SELECTOR_4_ALL",
        "FUEL_SELECTOR_4_LEFT",
        "FUEL_SELECTOR_4_RIGHT",
        "FUEL_SELECTOR_4_LEFT_AUX",
        "FUEL_SELECTOR_4_RIGHT_AUX",
        "FUEL_SELECTOR_4_CENTER",
        "FUEL_SELECTOR_4_SET",
        "CROSS_FEED_OPEN",
        "CROSS_FEED_TOGGLE",
        "CROSS_FEED_OFF",
        "XPNDR",
        "ADF",
        "DME",
        "VOR_OBS",
        "NAV_RADIO",
        "NAV1_RADIO_WHOLE_DEC",
        "NAV1_RADIO_WHOLE_INC",
        "NAV1_RADIO_FRACT_DEC",
        "NAV1_RADIO_FRACT_INC",
        "NAV2_RADIO_WHOLE_DEC",
        "NAV2_RADIO_WHOLE_INC",
        "NAV2_RADIO_FRACT_DEC",
        "NAV2_RADIO_FRACT_INC",
        "ADF_100_INC",
        "ADF_10_INC",
        "ADF_1_INC",
        "XPNDR_1000_INC",
        "XPNDR_100_INC",
        "XPNDR_10_INC",
        "XPNDR_1_INC",
        "VOR1_OBI_DEC",
        "VOR1_OBI_INC",
        "VOR2_OBI_DEC",
        "VOR2_OBI_INC",
        "ADF_100_DEC",
        "ADF_10_DEC",
        "ADF_1_DEC",
        "NAV1_RADIO_SET",
        "NAV2_RADIO_SET",
        "ADF_SET",
        "VOR1_SET",
        "VOR2_SET",
        "DME1_TOGGLE",
        "DME2_TOGGLE",
        "RADIO_VOR1_IDENT_DISABLE",
        "RADIO_VOR2_IDENT_DISABLE",
        "RADIO_DME1_IDENT_DISABLE",
        "RADIO_DME2_IDENT_DISABLE",
        "RADIO_ADF_IDENT_DISABLE",
        "RADIO_VOR1_IDENT_ENABLE",
        "RADIO_VOR2_IDENT_ENABLE",
        "RADIO_DME1_IDENT_ENABLE",
        "RADIO_DME2_IDENT_ENABLE",
        "RADIO_ADF_IDENT_ENABLE",
        "RADIO_VOR1_IDENT_TOGGLE",
        "RADIO_VOR2_IDENT_TOGGLE",
        "RADIO_DME1_IDENT_TOGGLE",
        "RADIO_DME2_IDENT_TOGGLE",
        "RADIO_ADF_IDENT_TOGGLE",
        "RADIO_VOR1_IDENT_SET",
        "RADIO_VOR2_IDENT_SET",
        "RADIO_DME1_IDENT_SET",
        "RADIO_DME2_IDENT_SET",
        "RADIO_ADF_IDENT_SET",
        "ADF_CARD_INC",
        "ADF_CARD_DEC",
        "ADF_CARD_SET",
        "TOGGLE_DME",
        "NAV1_RADIO_FRACT_DEC_CARRY",
        "NAV1_RADIO_FRACT_INC_CARRY",
        "NAV1_STBY_SET",
        "NAV1_RADIO_SWAP",
        "NAV2_RADIO_FRACT_DEC_CARRY",
        "NAV2_RADIO_FRACT_INC_CARRY",
        "NAV2_STBY_SET",
        "NAV2_RADIO_SWAP",
        "ADF1_RADIO_TENTHS_DEC",
        "ADF1_RADIO_TENTHS_INC",
        "XPNDR_1000_DEC",
        "XPNDR_100_DEC",
        "XPNDR_10_DEC",
        "XPNDR_1_DEC",
        "XPNDR_DEC_CARRY",
        "XPNDR_INC_CARRY",
        "ADF_FRACT_DEC_CARRY",
        "ADF_FRACT_INC_CARRY",
        "MARKER_SOUND_TOGGLE",
        "ADF_COMPLETE_SET",
        "ADF1_WHOLE_INC",
        "ADF1_WHOLE_DEC",
        "ADF2_100_INC",
        "ADF2_10_INC",
        "ADF2_1_INC",
        "ADF2_RADIO_TENTHS_INC",
        "ADF2_100_DEC",
        "ADF2_10_DEC",
        "ADF2_1_DEC",
        "ADF2_RADIO_TENTHS_DEC",
        "ADF2_WHOLE_INC",
        "ADF2_WHOLE_DEC",
        "ADF2_FRACT_DEC_CARRY",
        "ADF2_FRACT_INC_CARRY",
        "ADF2_COMPLETE_SET",
        "RADIO_ADF2_IDENT_DISABLE",
        "RADIO_ADF2_IDENT_ENABLE",
        "RADIO_ADF2_IDENT_TOGGLE",
        "RADIO_ADF2_IDENT_SET",
        "FREQUENCY_SWAP",
        "TOGGLE_GPS_DRIVES_NAV1",
        "GPS_POWER_BUTTON",
        "GPS_NEAREST_BUTTON",
        "GPS_OBS_BUTTON",
        "GPS_MSG_BUTTON",
        "GPS_MSG_BUTTON_DOWN",
        "GPS_MSG_BUTTON_UP",
        "GPS_FLIGHTPLAN_BUTTON",
        "GPS_TERRAIN_BUTTON",
        "GPS_PROCEDURE_BUTTON",
        "GPS_ZOOMIN_BUTTON",
        "GPS_ZOOMOUT_BUTTON",
        "GPS_DIRECTTO_BUTTON",
        "GPS_MENU_BUTTON",
        "GPS_CLEAR_BUTTON",
        "GPS_CLEAR_ALL_BUTTON",
        "GPS_CLEAR_BUTTON_DOWN",
        "GPS_CLEAR_BUTTON_UP",
        "GPS_ENTER_BUTTON",
        "GPS_CURSOR_BUTTON",
        "GPS_GROUP_KNOB_INC",
        "GPS_GROUP_KNOB_DEC",
        "GPS_PAGE_KNOB_INC",
        "GPS_PAGE_KNOB_DEC",
        "EGT",
        "EGT_INC",
        "EGT_DEC",
        "EGT_SET",
        "BAROMETRIC",
        "GYRO_DRIFT_INC",
        "GYRO_DRIFT_DEC",
        "KOHLSMAN_INC",
        "KOHLSMAN_DEC",
        "KOHLSMAN_SET",
        "TRUE_AIRSPEED_CAL_INC",
        "TRUE_AIRSPEED_CAL_DEC",
        "TRUE_AIRSPEED_CAL_SET",
        "EGT1_INC",
        "EGT1_DEC",
        "EGT1_SET",
        "EGT2_INC",
        "EGT2_DEC",
        "EGT2_SET",
        "EGT3_INC",
        "EGT3_DEC",
        "EGT3_SET",
        "EGT4_INC",
        "EGT4_DEC",
        "EGT4_SET",
        "ATTITUDE_BARS_POSITION_UP",
        "ATTITUDE_BARS_POSITION_DOWN",
        "ATTITUDE_CAGE_BUTTON",
        "RESET_G_FORCE_INDICATOR",
        "RESET_MAX_RPM_INDICATOR",
        "HEADING_GYRO_SET",
        "GYRO_DRIFT_SET",
        "ALL_LIGHTS_TOGGLE",
        "LANDING_LIGHT_UP",
        "LANDING_LIGHT_DOWN",
        "LANDING_LIGHT_LEFT",
        "LANDING_LIGHT_RIGHT",
        "LANDING_LIGHT_HOME",
        "TOGGLE_VACUUM_FAILURE",
        "TOGGLE_ELECTRICAL_FAILURE",
        "TOGGLE_PITOT_BLOCKAGE",
        "TOGGLE_STATIC_PORT_BLOCKAGE",
        "TOGGLE_HYDRAULIC_FAILURE",
        "TOGGLE_TOTAL_BRAKE_FAILURE",
        "TOGGLE_LEFT_BRAKE_FAILURE",
        "TOGGLE_RIGHT_BRAKE_FAILURE",
        "TOGGLE_ENGINE1_FAILURE",
        "TOGGLE_ENGINE2_FAILURE",
        "TOGGLE_ENGINE3_FAILURE",
        "TOGGLE_ENGINE4_FAILURE",
        "BRAKES",
        "BRAKES_LEFT",
        "BRAKES_RIGHT",
        "PARKING_BRAKES",
        "GEAR_PUMP",
        "PITOT_HEAT_ON",
        "PITOT_HEAT_OFF",
        "PITOT_HEAT_SET",
        "TOGGLE_ELECTRIC_VACUUM_PUMP",
        "DECREASE_DECISION_HEIGHT",
        "INCREASE_DECISION_HEIGHT",
        "TOGGLE_STRUCTURAL_DEICE",
        "TOGGLE_PROPELLER_DEICE",
        "TOGGLE_MASTER_BATTERY_ALTERNATOR",
        "AXIS_LEFT_BRAKE_SET",
        "AXIS_RIGHT_BRAKE_SET",
        "TOGGLE_AIRCRAFT_EXIT",
        "TOGGLE_WING_FOLD",
        "SET_WING_FOLD",
        "TOGGLE_TAIL_HOOK_HANDLE",
        "SET_TAIL_HOOK_HANDLE",
        "TOGGLE_WATER_RUDDER",
        "TOGGLE_PUSHBACK",
        "TUG_DISABLE",
        "TOGGLE_MASTER_IGNITION_SWITCH",
        "TOGGLE_TAILWHEEL_LOCK",
        "ADD_FUEL_QUANTITY",

    ];
    let mut counter = 0;
    for event in event_list.into_iter() {
        conn.map_client_event_to_sim_event(counter, event);
        conn.add_client_event_to_notification_group(0, counter, true);
        counter += 1;
    }
    conn.set_notification_group_priority(1, 1); 
}